jobs:
  build:
    environment:
      ONEDRIVE_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJub25jZSI6Im1uWXZsZlFISklZVVlUOWNIWldXQk1idHdkY3dBMmRxTV8yeDMtUHJoSDAiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC80MzUwYjU4ZC02MzZkLTRkYWYtYTBmZi05N2Q2NzBmZDlhOTgvIiwiaWF0IjoxNjg1OTkwODQwLCJuYmYiOjE2ODU5OTA4NDAsImV4cCI6MTY4NjA3NzU0MCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkUyWmdZTGpqcDZiR0VDQlFhbGpKa3JQQmFYSDJkMGJUbXB0ZXUyb3pwaDFabWxRZ3lqQTMxRGt4OFJrRFE3RDBqN2o5eklvOUFBPT0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIEV4cGxvcmVyIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IkFodGVzaGFtIEFobWFkIiwiZ2l2ZW5fbmFtZSI6Ik1EIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMjQwNjo3NDAwOmM4OmJhYTY6OTAyMDo1MDQyOmJjNmE6NzI3OCIsIm5hbWUiOiJNRCBBaHRlc2hhbSBBaG1hZCIsIm9pZCI6ImI0YzBhNjljLThlOGQtNDA4Zi05ZWEyLWRkOTI4NDg0N2JmNyIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwMjVEMkJCRUVEIiwicmgiOiIwLkFWTUFqYlZRUTIxanIwMmdfNWZXY1AyYW1BTUFBQUFBQUFBQXdBQUFBQUFBQUFCVEFJRS4iLCJzY3AiOiJGaWxlcy5SZWFkIEZpbGVzLlJlYWRXcml0ZSBvcGVuaWQgcHJvZmlsZSBVc2VyLlJlYWQgZW1haWwiLCJzaWduaW5fc3RhdGUiOlsia21zaSJdLCJzdWIiOiJsUmJVVFQ5ZVBQSnc0bldTVkFxUE14WEVWUGFtRHBBamNhZEMxNWMwN2g0IiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkFTIiwidGlkIjoiNDM1MGI1OGQtNjM2ZC00ZGFmLWEwZmYtOTdkNjcwZmQ5YTk4IiwidW5pcXVlX25hbWUiOiJtZGFodGVzaGFtYWhtYWRAbnNlaXQuY29tIiwidXBuIjoibWRhaHRlc2hhbWFobWFkQG5zZWl0LmNvbSIsInV0aSI6InBZczZjV3dNV0VLMXdNUUg2ZUViQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2MiOlsiQ1AxIl0sInhtc19zc20iOiIxIiwieG1zX3N0Ijp7InN1YiI6IjFDTmNodm5LSjhfRU1kalJ6eHBONkZtYkVkNUZmWE04YktXemI1dndZTGsifSwieG1zX3RjZHQiOjE1NDY5NDU2NjR9.SvAJNWAyaCmdfoMSm_nhbYp5-usRTFYSB_LtKdfG3pGO-KTMksFXw7L9pcpB3zkr1B96hOL55ilIlyg14DR_5akn37bZmsj3TX8Wkl9nUhS8LK55T6KkWT4bNVxuYfX1njJTCJkH0JnZvrKRfOSCB_R5rdk_qjh8xxVcg4IQQe4Xdxx3xeDPAYzPkiRmBBHbysxe5Lw8cWcXAWW2M6pzHnIXDQaOT3rJ1dxd3IEEBv0v4l0Q2muKWKarjevpNxnEK6JbXCasF0DSoGa0whNFaFE1R4ll7jxhOEwDu4UYJ6udNd2PhyKO0wUtVBaGvQoxR_4aCvLWR92C6KSdsWyHsQ
    docker:
      - image: circleci/node:14

    steps:
    - run:
        name: Create artifact
        command: |
          echo "Hi, This is Md and want to upload artifact file." > MyPersonal.txt
    - run:
        name: Upload to OneDrive
        command: |
          export ARTIFACT_PATH=$MyPersonal.txt
          export FILE_CONTENT=$(base64 -w 0 "$ARTIFACT_PATH")
          export FILE_NAME=$(basename "$ARTIFACT_PATH")
          CREATE_RESPONSE=$(curl -X POST \
            -H "Authorization: Bearer $ONEDRIVE_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"$FILE_NAME\", \"file\": {}}" \
            "https://graph.microsoft.com/v1.0/me/drive/root/children")
          if [ "$(echo "$CREATE_RESPONSE" | jq -r '.error')" != "null" ]; then
            echo "Error creating the file:"
            echo "$CREATE_RESPONSE"
            exit 1
          fi
          FILE_ID=$(echo "$CREATE_RESPONSE" | jq -r '.id')
          UPLOAD_RESPONSE=$(curl -X PUT \
          -H "Authorization: Bearer $ONEDRIVE_ACCESS_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary "@$ARTIFACT_PATH" \
          "https://graph.microsoft.com/v1.0/me/drive/items/$FILE_ID/content")
          if [ "$(echo "$UPLOAD_RESPONSE" | jq -r '.error')" != "null" ]; then
            echo "Error uploading file content:"
            echo "$UPLOAD_RESPONSE"
            exit 1
          fi
          # Check the response from the upload request
          echo "File uploaded successfully."

            