jobs:
  build:
    environment:
      ONEDRIVE_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJub25jZSI6IjNsSjhHb0Fval9EN0RGT2FHS3ZCcFBSM1lKOGRFd29DLWFDM0hIRHJmQ0EiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC80MzUwYjU4ZC02MzZkLTRkYWYtYTBmZi05N2Q2NzBmZDlhOTgvIiwiaWF0IjoxNjg1ODk1NDQ3LCJuYmYiOjE2ODU4OTU0NDcsImV4cCI6MTY4NTk4MjE0NywiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhUQUFBQXpqSWFmNVNzUDdJMUZCSTZVamgrVHhBZjM4VzNZU1g1dVZvY2FEMDhXUWZQTlUyaXhDbUp2MHN3Zzh6SVdQaWMiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIEV4cGxvcmVyIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IkFodGVzaGFtIEFobWFkIiwiZ2l2ZW5fbmFtZSI6Ik1EIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMjQwNjo3NDAwOmM4OmJhYTY6ZDQyMzoyZGM2Ojg0NWU6M2Q3NiIsIm5hbWUiOiJNRCBBaHRlc2hhbSBBaG1hZCIsIm9pZCI6ImI0YzBhNjljLThlOGQtNDA4Zi05ZWEyLWRkOTI4NDg0N2JmNyIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwMjVEMkJCRUVEIiwicmgiOiIwLkFWTUFqYlZRUTIxanIwMmdfNWZXY1AyYW1BTUFBQUFBQUFBQXdBQUFBQUFBQUFCVEFJRS4iLCJzY3AiOiJGaWxlcy5SZWFkIEZpbGVzLlJlYWRXcml0ZSBvcGVuaWQgcHJvZmlsZSBVc2VyLlJlYWQgZW1haWwiLCJzaWduaW5fc3RhdGUiOlsia21zaSJdLCJzdWIiOiJsUmJVVFQ5ZVBQSnc0bldTVkFxUE14WEVWUGFtRHBBamNhZEMxNWMwN2g0IiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkFTIiwidGlkIjoiNDM1MGI1OGQtNjM2ZC00ZGFmLWEwZmYtOTdkNjcwZmQ5YTk4IiwidW5pcXVlX25hbWUiOiJtZGFodGVzaGFtYWhtYWRAbnNlaXQuY29tIiwidXBuIjoibWRhaHRlc2hhbWFobWFkQG5zZWl0LmNvbSIsInV0aSI6Ikp0VG5qcUN1alVtY3NoTWtjVnRnQVEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2MiOlsiQ1AxIl0sInhtc19zc20iOiIxIiwieG1zX3N0Ijp7InN1YiI6IjFDTmNodm5LSjhfRU1kalJ6eHBONkZtYkVkNUZmWE04YktXemI1dndZTGsifSwieG1zX3RjZHQiOjE1NDY5NDU2NjR9.oIhxJ5wI_WJO3Tz5hPonT6SFETteXDkdlp6Zegsoi-EOn7RM8Bp-Qwvr_90LMPqH5hmlmMzVa7-cpmYiH7-Bw4vIxQeDtgtVjGtGhPCbSq4KdM6SZQtt2ob1yxEF4PYil_u9kE_ZpKMuXXB4qvtZW6SjEZLW52tMsp_pTReCknPbWGlqs7h8fADpzB28BMmdxqlmSdqeYQljj0n7pM1PAwGLeNmS1XbDjllcuIZKxZVwEJLDFAqlRe0-EJEZhsu-2Q1_ZldkbplHwi5fvt53VOXqeFo4CvvduGsxL71vigFnZjVX64xBRfyhJGQEV_JEH8TP7En83iNVq55zPn_Kug
    docker:
      - image: circleci/node:14

    steps:
    - run:
        name: Create artifact
        command: |
          echo "This is an example artifact" > example.txt
    - run:
        name: Upload to OneDrive
        command: |
          export ARTIFACT_PATH=example.txt
          export FILE_CONTENT=$(base64 -w 0 "$ARTIFACT_PATH")
          export FILE_NAME=$(basename "$ARTIFACT_PATH")
          CREATE_RESPONSE=$(curl -X POST \
            -H "Authorization: Bearer $ONEDRIVE_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"$FILE_NAME\", \"file\": {}}" \
            "https://graph.microsoft.com/v1.0/me/drive/root/children")
          if [ "$(echo "$CREATE_RESPONSE" | jq -r '.error')" != "null" ]; then
            echo "Error creating the file:"
            echo "$CREATE_RESPONSE"
            exit 1
          fi
          FILE_ID=$(echo "$CREATE_RESPONSE" | jq -r '.id')
          UPLOAD_RESPONSE=$(curl -X PUT \
          -H "Authorization: Bearer $ONEDRIVE_ACCESS_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary "@$ARTIFACT_PATH" \
          "https://graph.microsoft.com/v1.0/me/drive/items/$FILE_ID/content")
          if [ "$(echo "$UPLOAD_RESPONSE" | jq -r '.error')" != "null" ]; then
            echo "Error uploading file content:"
            echo "$UPLOAD_RESPONSE"
            exit 1
          fi
          # Check the response from the upload request
          echo "File uploaded successfully."

            