jobs:
  build:
    environment:
      ONEDRIVE_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJub25jZSI6Iks3MVIydndYMnR3eHJLU1czNm9GSVhGaUowMkFYU0dSZ0k4X1FGTTgwNUEiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC80MzUwYjU4ZC02MzZkLTRkYWYtYTBmZi05N2Q2NzBmZDlhOTgvIiwiaWF0IjoxNjg2MTUyMzcxLCJuYmYiOjE2ODYxNTIzNzEsImV4cCI6MTY4NjE1NjI3MSwiYWlvIjoiRTJaZ1lOam1kR2IzMnRsTXpXME5tNzVscmtpcEJ3QT0iLCJhcHBfZGlzcGxheW5hbWUiOiJQZXJzb25hbEFjY2Vzc0ZvckZpbGVVcGxvYWRpbmciLCJhcHBpZCI6ImNjZDFkMDFlLTcyNDgtNDg0Yy1hM2Y4LWM0MzU3NmY0NjIyNSIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzQzNTBiNThkLTYzNmQtNGRhZi1hMGZmLTk3ZDY3MGZkOWE5OC8iLCJpZHR5cCI6ImFwcCIsIm9pZCI6ImQ0ODE4NGVkLWJhMWMtNDllMi1iOTkzLWQ4YTc3NjBkN2M1NiIsInJoIjoiMC5BVk1BamJWUVEyMWpyMDJnXzVmV2NQMmFtQU1BQUFBQUFBQUF3QUFBQUFBQUFBQlRBQUEuIiwic3ViIjoiZDQ4MTg0ZWQtYmExYy00OWUyLWI5OTMtZDhhNzc2MGQ3YzU2IiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkFTIiwidGlkIjoiNDM1MGI1OGQtNjM2ZC00ZGFmLWEwZmYtOTdkNjcwZmQ5YTk4IiwidXRpIjoiVE1feTdpWU11MEdib1dRUGF4dy1BQSIsInZlciI6IjEuMCIsIndpZHMiOlsiMDk5N2ExZDAtMGQxZC00YWNiLWI0MDgtZDVjYTczMTIxZTkwIl0sInhtc190Y2R0IjoxNTQ2OTQ1NjY0fQ.nxjm44rOlWVv1gsNLoegcsa1985-RwP-nH1mbyvS0eVJIh6k8Sej_HVOGY93oosnIkU9SSrDvk4-Lb5Y8T8NVgXtq3VVc_ut-ELSOo1-ipyfBF2V12SJLyvkS2kIiCAT3Xn9ypAAtD9ieFiGITcA_bduwHXpa7LoxVYK6M7WNjdw4u5GSyxFhj4iooJhTDK5aVQVCJcy5jb0SZAlsCfUQPXp-p31Tz1VBym4p5GE1odUFmoYre2oj8JZkELzYs9cMMewlJpXnU1W48oB24CJpWaYLMm-RylLa0r1nlLb3wml0wpV0HPfLVX9JavAmZpiij0RSmMK94Odm9YOAsAiuQ
    docker:
      - image: circleci/node:14

    steps:
    - run:
        name: Create artifact
        command: |
          echo "Hi, This is Md and want to upload artifact file in onedrive." > AccessFile.txt
    - run:
        name: Upload to OneDrive
        command: |
          export ARTIFACT_PATH=AccessFile.txt
          export FILE_CONTENT=$(base64 -w 0 "$ARTIFACT_PATH")
          export FILE_NAME=$(basename "$ARTIFACT_PATH")
          CREATE_RESPONSE=$(curl -X POST \
            -H "Authorization: Bearer $ONEDRIVE_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"$FILE_NAME\", \"file\": {}}" \
            "https://graph.microsoft.com/v1.0/me/drive/root/children")
          if [ "$(echo "$CREATE_RESPONSE" | jq -r '.error')" != "null" ]; then
            echo "Error creating the file:"
            echo "$CREATE_RESPONSE"
            exit 1
          fi
          FILE_ID=$(echo "$CREATE_RESPONSE" | jq -r '.id')
          UPLOAD_RESPONSE=$(curl -X PUT \
          -H "Authorization: Bearer $ONEDRIVE_ACCESS_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary "@$ARTIFACT_PATH" \
          "https://graph.microsoft.com/v1.0/me/drive/items/$FILE_ID/content")
          if [ "$(echo "$UPLOAD_RESPONSE" | jq -r '.error')" != "null" ]; then
            echo "Error uploading file content:"
            echo "$UPLOAD_RESPONSE"
            exit 1
          fi
          # Check the response from the upload request
          echo "File uploaded successfully."

            